name: 'git-dash.com'
author: 'ToyB0x'
description: 'Analyze git activity'
branding:
  color: 'blue'
  icon: 'activity'
inputs:
  target-repositories:
    description: |-
      List of repositories to analyze. These are newline-separated.
      If not provided, all repositories that the token can access to will be analyzed.

      Example:
      ```yml
      target-repositories: |-
        OWNER/REPO1
        OWNER/REPO2
      ```
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        repository: 'ToyB0x/git-dash'

    - name: Enable corepack for pnpm
      run: corepack enable pnpm
      shell: bash

    - name: Setup & Restore Node cache
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        cache: 'pnpm'
        node-version-file: 'package.json'

    - name: Install all packages
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Build all packages
      run: pnpm turbo build --filter=@repo/jobs
      shell: bash

    - name: Echo
      run: echo $TARGET_REPOSITORIES
      shell: bash
      env:
        TARGET_REPOSITORIES: ${{ inputs.target-repositories }}

    - name: Curl test
      run: curl api.git-dash.com
      shell: bash
