name: 'git-dash.com'
author: 'ToyB0x'
description: 'Analyze git activity'
inputs:
  target-repositories:
    description: |-
      List of repositories to analyze. These are newline-separated.
      If not provided, all repositories that the token can access to will be analyzed.

      Example:
      ```yml
      target-repositories: |-
        OWNER/REPO1
        OWNER/REPO2
      ```
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - echo
    - ${{ inputs.target-repositories }}
branding:
  color: 'blue'
  icon: 'activity'
