name: 'git-dash.com'
author: 'ToyB0x'
description: 'Analyze git activity'
branding:
  color: 'blue'
  icon: 'activity'
inputs:
  target-repositories:
    description: |-
      List of repositories to analyze. These are newline-separated.
      If not provided, all repositories that the token can access to will be analyzed.

      Example:
      ```yml
      target-repositories: |-
        OWNER/REPO1
        OWNER/REPO2
      ```
    required: true
  GDASH_GITHUB_ORGANIZATION_NAME:
    description: "GitHub organization name to analyze"
    required: true
  GDASH_GROUP_ID:
    description: "Group ID to send report"
    required: true
  GDASH_GROUP_API_KEY:
    description: "Group API key to send report"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        repository: 'ToyB0x/git-dash'

    - name: Enable corepack for pnpm
      run: corepack enable pnpm
      shell: bash

    - name: Setup & Restore Node cache
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        cache: 'pnpm'
        node-version-file: 'package.json'

    - name: Install all packages
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Build all packages
      run: pnpm turbo build --filter=@repo/jobs
      shell: bash

    - name: Env Check
      run: pnpm jobs export check
      shell: bash
      working-directory: apps/jobs
      env:
        GDASH_GITHUB_ORGANIZATION_NAME: ${{ inputs.GDASH_GITHUB_ORGANIZATION_NAME }}
        GDASH_GROUP_ID: ${{ inputs.GDASH_GROUP_ID }}
        GDASH_GROUP_API_KEY: ${{ inputs.GDASH_GROUP_API_KEY }}
