name = "gdash-api"
main = "src/index.ts"
compatibility_date = "2024-12-04"
routes = [
    { pattern = "api.git-dash.com", custom_domain = true }
]

[limits]
cpu_ms = 100 # To prevent accidental runaway bills or denial-of-wallet attacks (maybe ignored on free-plan)

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "REPORT_BUCKET"
bucket_name = "report-prd"

[[ d1_databases ]]
binding = "DB_API"
database_name = "gdash-prd" # just management displayName (not used programatically)
database_id = "34cdcf5e-6899-41ff-b694-40d85e68d6e3"
migrations_dir = "drizzle/migrations" # load as symlink from packages/[db-package-name]/wrangler.toml

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1