// Generated by Wrangler by running `wrangler types`

interface Env {
	PUBLIC_JWK_CACHE_KV: KVNamespace;
	PUBLIC_JWK_CACHE_KEY: "public-jwk-cache-key";
	PUBLIC_FIREBASE_PROJECT_ID: string;
	REPORT_BUCKET: R2Bucket;
	DB_API: D1Database;
}
