// Generated by Wrangler by running `wrangler types --config ./wrangler-local.toml`

interface Env {
	PUBLIC_JWK_CACHE_KV: KVNamespace;
	PUBLIC_JWK_CACHE_KEY: "public-jwk-cache-key";
	PUBLIC_FIREBASE_PROJECT_ID: string;
	BUCKET_DB_REPORT: R2Bucket;
	BUCKET_DB_REPORT_SAMPLE: R2Bucket;
	DB_API: D1Database;
}
