name = "gdash-api-local"
main = "src/index.ts"
compatibility_date = "2024-12-04"

[limits]
cpu_ms = 100 # To prevent accidental runaway bills or denial-of-wallet attacks (maybe ignored on free-plan)

[vars]
PUBLIC_FIREBASE_PROJECT_ID = "local"
PUBLIC_JWK_CACHE_KEY = "public-jwk-cache-key"

# compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "PUBLIC_JWK_CACHE_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "BUCKET_DB_REPORT"
bucket_name = "gdash-report-local"

[[r2_buckets]]
binding = "BUCKET_DB_REPORT_SAMPLE"
bucket_name = "gdash-report-local-sample"

[[ d1_databases ]]
binding = "DB_API"
database_name = "gdash-local" # just management displayName (not used programatically)
database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
migrations_dir = "drizzle" # relative path from packages/[db-package-name]/wrangler.toml

[observability.logs]
enabled = true
head_sampling_rate = 1
