name = "gdash-api-stg"
main = "src/index.ts"
compatibility_date = "2024-12-04"

[vars]
PUBLIC_FIREBASE_PROJECT_ID = "git-dash-stg"
PUBLIC_JWK_CACHE_KEY = "public-jwk-cache-key"

# compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "PUBLIC_JWK_CACHE_KV"
id = "a4c321033a0c4a8ab3fbe59a3e271f16" # kv_namespace=gdash-stg

[[r2_buckets]]
binding = "BUCKET_DB_REPORT"
bucket_name = "gdash-report-stg"

[[r2_buckets]]
binding = "BUCKET_DB_REPORT_SAMPLE"
bucket_name = "gdash-report-stg-sample"

[[ d1_databases ]]
binding = "DB_API"
database_name = "gdash-stg" # just management displayName (not used programatically)
database_id = "b30b5da8-7662-497a-8a96-b23db3b864bd"
migrations_dir = "drizzle" # relative path from packages/[db-package-name]/wrangler.toml

# [ai]
# binding = "AI"

[observability.logs]
enabled = true
head_sampling_rate = 1
