name: marketplace
on:
  push:
  workflow_dispatch:

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: run marketplace action
        uses: './' # Uses an action in the root directory
        with:
          GDASH_PROJECT_ID: "test-project-id"
          GDASH_GITHUB_ORGANIZATION_NAME: "test-org-name"
          GDASH_GITHUB_PERSONAL_ACCESS_TOKEN: "test-personal-access-token"
          GDASH_GROUP_ID: "test-group-id"
          GDASH_GROUP_API_KEY: "test-group-api-key"
          target-repositories: |-
            OWNER/REPO1
            OWNER/REPO2
