name: marketplace
on:
  push:
  workflow_dispatch:

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: run marketplace action test as ORGANIZATION_APP MODE
        uses: './' # Uses an action in the root directory
        with:
          GDASH_ENV: "dev"
          GDASH_MODE: "ORGANIZATION_APP" # ORGANIZATION_APP | SINGLE_REPOSITORY | SAMPLE
          GDASH_GITHUB_ORGANIZATION_NAME: "test-org-name" # TODO: ORGANIZATION_APP | SINGLE_REPOSITORY モードのどちらでもActionsの環境変数から取得できるので削除する
          GDASH_GITHUB_INTERNAL_APP_ID: "12345678"
          GDASH_GITHUB_INTERNAL_APP_PRIVATE_KEY_STRING: "-----BEGIN RSA PRIVATE KEY-----\nXXXXXX\n-----END RSA PRIVATE KEY-----"
          GDASH_WORKSPACE_ID: "test-group-id" # NOTE: 技術的にはTokenに含められるが、ユーザ自身が後で再確認しやすいようにymlに直接記載できるように残しておく
          GDASH_WORKSPACE_API_KEY: "test-group-api-key"
          GDASH_COLLECT_DAYS_LIGHT_TYPE_ITEMS: 180
          GDASH_COLLECT_DAYS_HEAVY_TYPE_ITEMS: 60
          GDASH_DISCARD_DAYS: 180
          ONLY_CONFIG_CHECK: 'true'

      - name: run marketplace action test as SINGLE_REPOSITORY MODE
        uses: './' # Uses an action in the root directory
        with:
          GDASH_ENV: "dev"
          GDASH_MODE: "SINGLE_REPOSITORY" # ORGANIZATION_APP | SINGLE_REPOSITORY | SAMPLE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDASH_GITHUB_ORGANIZATION_NAME: "test-org-name" # TODO: ORGANIZATION_APP | SINGLE_REPOSITORY モードのどちらでもActionsの環境変数から取得できるので削除する
          GDASH_WORKSPACE_ID: "test-group-id" # NOTE: 技術的にはTokenに含められるが、ユーザ自身が後で再確認しやすいようにymlに直接記載できるように残しておく
          GDASH_WORKSPACE_API_KEY: "test-group-api-key"
          GDASH_COLLECT_DAYS_LIGHT_TYPE_ITEMS: 180
          GDASH_COLLECT_DAYS_HEAVY_TYPE_ITEMS: 60
          GDASH_DISCARD_DAYS: 180
          ONLY_CONFIG_CHECK: 'true'
