name: marketplace
on:
  push:
  workflow_dispatch:

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: run marketplace action
        uses: './' # Uses an action in the root directory
        with:
          GDASH_ENV: "dev"
          GDASH_GITHUB_ORGANIZATION_NAME: "test-org-name"
          GDASH_GITHUB_INTERNAL_APP_ID: "12345678"
          GDASH_GITHUB_INTERNAL_APP_PRIVATE_KEY_STRING: "-----BEGIN RSA PRIVATE KEY-----\nXXXXXX\n-----END RSA PRIVATE KEY-----"
          GDASH_WORKSPACE_ID: "test-group-id"
          GDASH_WORKSPACE_API_KEY: "test-group-api-key"
          GDASH_COLLECT_DAYS: 30
          GDASH_DISCARD_DAYS: 180
          ONLY_CONFIG_CHECK: 'true'
