name: deploy-prd
on:
  release:
    types:
      - published

permissions:
  contents: read # for checkout repository

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    uses: ./.github/workflows/deploy-base.yml
    with:
      environment: production
    secrets: inherit
