name: deploy-dev
on:
  push:
    branches:
      - main

permissions:
  contents: write # for checkout repository and updating tag

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-cloudflare:
    uses: ./.github/workflows/deploy-base.yml
    with:
      environment: development
    secrets: inherit

  deploy-github-action:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Update dev tag
      run: pnpm run:update-tag dev
      working-directory: apps/cli-admin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
