name: deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout repository

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy
        uses: ToyB0x/git-dash/.github/workflows/deploy-base.yml@main
        with:
          environment: development
          # secrets: inherit