name: deploy
on: push

permissions:
  contents: read # for checkout repository

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-base.yml
    with:
      environment: 'development'
    secrets: inherit
