name: deploy
on: push

permissions:
  contents: read # for checkout repository

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Deploy
        uses: ./.github/workflows/deploy-base.yml@feat/deploy-ci
        with:
          environment: development
          secrets: inherit
