name: deploy-dev
on:
  push:
    branches:
      - main

permissions:
  contents: write # for checkout repository and updating tag

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-cloudflare:
    uses: ./.github/workflows/deploy-base.yml
    with:
      environment: development
    secrets: inherit

  deploy-github-action:
    uses: ./.github/workflows/update-tag-base.yml
    with:
      tag: dev
