name: deploy
on: push

permissions:
  contents: read # for checkout repository

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy
        run: echo "Deploying to development"
#      - name: Deploy
#        uses: ToyB0x/git-dash/.github/workflows/deploy-base.yml@feat/deploy-ci
#        with:
#          environment: development
#          # secrets: inherit
