on:
  workflow_call:
    inputs:
      environment:
        default: development
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      VITE_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.VITE_PUBLIC_FIREBASE_PROJECT_ID }}
      VITE_PUBLIC_FIREBASE_BROWSER_API_KEY: ${{ secrets.VITE_PUBLIC_FIREBASE_BROWSER_API_KEY }}
      VITE_PUBLIC_API_SERVER_URL: ${{ secrets.VITE_PUBLIC_API_SERVER_URL }}
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Enable corepack for pnpm
        run: corepack enable pnpm

      - name: Setup & Restore Node cache
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Restore turbo cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: .turbo/cache
          key:
            turbo/${{ github.job }}/${{ github.ref_name }}/${{ github.sha }}
          restore-keys: |
            turbo/${{ github.job }}/${{ github.ref_name }}/
            turbo/${{ github.job }}/

      - name: Type check
        run: pnpm typecheck

      - name: Build check
        run: pnpm build

      - name: deploy api
        run: pnpm deploy:${{ inputs.enviroment }}
        working-directory: apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: deploy web
        run: pnpm deploy:${{ inputs.enviroment }}
        working-directory: apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
