name: E2E
on:
  push:
  workflow_dispatch:

permissions:
  contents: read # for checkout repository

env:
  VITE_PUBLIC_FIREBASE_PROJECT_ID: 'local'
  VITE_PUBLIC_FIREBASE_BROWSER_API_KEY: 'local'
  VITE_PUBLIC_API_SERVER_URL: 'http://localhost:8787'
  VITE_PUBLIC_LOG_ROCKET_ID: 'local'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Enable corepack for pnpm
        run: npm install -g corepack@latest && corepack enable pnpm

      - name: Setup & Restore Node cache
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Restore turbo cache
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
        with:
          path: .turbo/cache
          key:
            turbo/${{ github.job }}/${{ github.ref_name }}/${{ github.sha }}
          restore-keys: |
            turbo/${{ github.job }}/${{ github.ref_name }}/
            turbo/${{ github.job }}/

      - name: Setup Playwright Browsers / Start Monorepo E2E
        run: pnpm e2e:run

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: E2E/internal/playwright-report/
          retention-days: 5
