name: schema-check
on:
  pull_request:
    paths:
      - 'packages/db-api/src/**'
      - 'packages/db-shared/src/**'

permissions:
  contents: read # for checkout repository
  pull-requests: write # for creating comments

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create comment file
        run: |
          cat  << EOF > comment.md
          ### :bell: The schema has changed. :bell:

          - [ ] Please run drizzle-kit generate to ensure new schema files are generated.
          - [ ] Please check the impact on users using older DB versions.

          EOF

      - name: Create PR comment
        run: |
          gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
