name: update-tag
on:
  push

permissions:
  contents: read # for checkout repository

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Enable corepack for pnpm
        run: corepack enable pnpm

      - name: Setup & Restore Node cache
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Update dev tag
        run: pnpm run:update-tag:dev
        working-directory: apps/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}