name: update-tag
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  update-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Enable corepack for pnpm
        run: npm install -g corepack@latest && corepack enable pnpm

      - name: Setup & Restore Node cache
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Update tag
        run: pnpm run:update-tag ${{ inputs.tag }}
        working-directory: apps/cli-admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
